name: C/C++ CI
on: [push]

jobs:
	build:
		runs-on: ubuntu-latest
	steps:
	- uses: actions/checkout@v2
	- name: build-reld
		run: make reld
	- name: build-mod1
		run: make mod1.mod
	- name: build-mod2
		run: make mod2.mod
	- name: check-loader
		run: reld mod2 mod1 mod1__main
